import Foundation

// MARK: - PinSet

/// The keys an app will accept for one host: the one serving today, the one
/// that will serve next, and any extra a migration is currently straddling.
///
/// The `backup` is not an optional nicety and is not a second copy of the
/// primary — it is the whole reason this app can rotate a key without shipping
/// a release. A pin set with one pin is a dead-man's switch: the day that key
/// is lost, compromised, or simply re-generated by a CA that would not reuse
/// it, every installed copy of the app stops being able to reach the API, and
/// the fix ships through review. The backup key is generated at the same time
/// as the primary, is never presented in a certificate until it is needed, and
/// is kept offline — see `docs/certificate-pinning.md`, which is the procedure
/// this type exists to make executable.
///
/// That the two are distinct is checked by
/// `CertificatePinningPolicy.problems(at:)` rather than by a precondition here.
/// A `precondition` would turn a configuration mistake into a crash on launch,
/// and a crash on launch is not a better outcome than a test failure — it is
/// the same defect discovered later, by a user.
package struct PinSet: Hashable, Sendable {

    /// The key in the certificate the server presents today.
    package let primary: PublicKeyPin

    /// The key held offline, in no certificate yet, that a rotation switches
    /// to. Distinct from `primary`, or the set cannot rotate at all.
    package let backup: PublicKeyPin

    /// Anything else that should be accepted for the duration of a migration —
    /// an issuing CA's key while a chain moves between authorities, or the
    /// outgoing key during the overlap window of a rotation already under way.
    ///
    /// Empty in the steady state, and it is meant to go back to empty: a pin
    /// set that accumulates keys accepts more issuers over time, which is the
    /// opposite of what pinning is for.
    package let additional: Set<PublicKeyPin>

    package init(primary: PublicKeyPin, backup: PublicKeyPin, additional: Set<PublicKeyPin> = []) {
        self.primary = primary
        self.backup = backup
        self.additional = additional
    }

    /// Every key this set accepts.
    package var all: Set<PublicKeyPin> {
        additional.union([primary, backup])
    }

    /// Whether the set can survive losing the primary key, which is the one
    /// property that distinguishes a rotation plan from a hope.
    package var canRotate: Bool { primary != backup }
}

// MARK: - Enforcement

/// What a pin mismatch does to the connection.
package enum PinEnforcement: Hashable, Sendable {

    /// The connection is refused. This is what pinning is for, and it is not
    /// where a new pin set should start: a pin that is wrong in a way nobody
    /// noticed takes the app off the network completely, for everybody, at
    /// once.
    case enforced

    /// The connection proceeds on the system's own verdict, and the mismatch
    /// is reported.
    ///
    /// This is the rollout position, and the reason the mode exists: ship the
    /// pins in report-only, watch for a release cycle, and turn enforcement on
    /// once the mismatch rate is zero. A CDN that silently serves two
    /// certificates, a corporate TLS-inspecting proxy on the office network, a
    /// staging host that shares the pinned domain — each is invisible until
    /// something counts it, and each is an outage if the first thing that
    /// counts it is enforcement.
    case reportOnly
}

// MARK: - HostPinningPolicy

/// What one host's pins are, how long they are good for, and what a mismatch
/// costs.
package struct HostPinningPolicy: Hashable, Sendable {

    /// A bare hostname: no scheme, no port, no path, no leading dot.
    package let host: String

    /// Whether `api.example.com`'s policy also covers `eu.api.example.com`.
    ///
    /// Off by default, because a wildcard pin is a promise about hosts that do
    /// not exist yet — including the one somebody stands up next quarter on a
    /// different CA.
    package let includesSubdomains: Bool

    /// The keys accepted for this host.
    package let pins: PinSet

    /// When this pin set stops being enforced.
    ///
    /// Not a bureaucratic field: it is the failure valve. Pins are a statement
    /// about a key, made at build time, shipped into copies of the app that may
    /// never be updated again. Without an expiry, the oldest installed version
    /// enforces its pins forever, so a key rotation eventually strands every
    /// user who stopped updating — silently, months later, with no path to a
    /// fix that does not involve the App Store. Past this date the policy
    /// degrades to the system's own trust evaluation, which is exactly what an
    /// app with no pinning does, and is a far better outcome than an app that
    /// cannot connect.
    ///
    /// `CertificatePinningPolicy.problems(at:)` refuses a date more than
    /// `maximumPinLifetime` away for the same reason: an expiry nobody will
    /// live to re-check is an expiry that is not a valve.
    package let expiry: Date

    /// What a mismatch does. See `PinEnforcement`.
    package let enforcement: PinEnforcement

    package init(
        host: String,
        pins: PinSet,
        expiry: Date,
        enforcement: PinEnforcement,
        includesSubdomains: Bool = false
    ) {
        self.host = host
        self.pins = pins
        self.expiry = expiry
        self.enforcement = enforcement
        self.includesSubdomains = includesSubdomains
    }

    /// Whether this policy governs `candidate`.
    ///
    /// Case-insensitive, because DNS is and because the hostname arrives from
    /// `URLProtectionSpace` rather than from this file. The subdomain test
    /// requires the dot to be part of the suffix: without it
    /// `evilapi.example.com` matches a policy for `api.example.com`, which is
    /// the classic way a hostname check is got wrong.
    package func governs(_ candidate: String) -> Bool {
        let candidate = candidate.lowercased()
        let host = host.lowercased()
        if candidate == host { return true }
        return includesSubdomains && candidate.hasSuffix("." + host)
    }

    /// Whether the pins have stopped being enforced as of `date`.
    package func hasExpired(at date: Date) -> Bool { date >= expiry }
}

// MARK: - CertificatePinningPolicy

/// Every host this app pins, and the audit of whether it pins them sensibly.
package struct CertificatePinningPolicy: Hashable, Sendable {

    /// The longest a pin set may be valid for.
    ///
    /// One year. The number is a judgement rather than a standard, and the
    /// judgement is about release cadence, not cryptography: the expiry has to
    /// be short enough that somebody re-reads the pins while the reasons for
    /// them are still true, and long enough that an app which misses a release
    /// does not fall out of pinning on its own. A year is roughly "every team
    /// revisits this once", which is the least often it can be revisited and
    /// still be revisited.
    package static let maximumPinLifetime: TimeInterval = 365 * 24 * 60 * 60

    /// The per-host policies, in no significant order — lookup is by hostname.
    package let hosts: [HostPinningPolicy]

    package init(hosts: [HostPinningPolicy]) {
        self.hosts = hosts
    }

    /// Pins nothing. Every connection falls through to the system's own trust
    /// evaluation, which is what an app without pinning does.
    ///
    /// Named `unpinned` rather than `none` because a static called `none` on a
    /// non-optional type reads as `Optional.none` at every call site that
    /// happens to be in optional context, and this value's whole job is to be
    /// unambiguous about what it switches off.
    package static let unpinned = CertificatePinningPolicy(hosts: [])

    /// The policy governing `host`, if any.
    ///
    /// An exact match wins over a subdomain match, so a policy for
    /// `api.example.com` is not shadowed by a wildcard policy for
    /// `example.com` that happens to be listed first.
    package func policy(for host: String) -> HostPinningPolicy? {
        let host = host.lowercased()
        if let exact = hosts.first(where: { $0.host.lowercased() == host }) {
            return exact
        }
        return hosts.first { $0.governs(host) }
    }
}

// MARK: - The audit

/// A way a pinning policy is wrong that no TLS handshake will report usefully.
///
/// Each of these produces, at runtime, either an ordinary-looking network
/// failure or no observable behaviour at all, and each is a property of the
/// policy value rather than of any connection — so each can be caught by
/// reading the policy, which is what `CertificatePinningPolicyTests` does to
/// the one this app ships.
package enum PinningPolicyProblem: Hashable, Sendable, CustomStringConvertible {

    /// Two entries claim the same hostname. One of them is unreachable, and
    /// which one depends on array order.
    case duplicateHost(String)

    /// A hostname with a scheme, a port, a path, a leading dot, or nothing at
    /// all. It will never equal a `URLProtectionSpace.host`, so the policy is
    /// inert: the app pins nothing and looks like it pins something.
    case hostIsNotABareHostname(String)

    /// The backup pin repeats the primary. The set cannot survive the loss of
    /// the primary key, which is the event it exists for.
    case backupRepeatsPrimary(host: String)

    /// The pins have already stopped being enforced.
    case expiryHasPassed(host: String, expiry: Date)

    /// The pins are valid for longer than `maximumPinLifetime`.
    case expiryIsTooDistant(host: String, expiry: Date)

    /// The template's placeholder pins are being enforced. See
    /// `PublicKeyPin.placeholders`: no real key hashes to either of them, so
    /// this is an app that can reach nothing at all.
    case placeholderPinsAreEnforced(host: String)

    package var description: String {
        switch self {
        case let .duplicateHost(host):
            "\(host) appears more than once; all but one entry is unreachable."
        case let .hostIsNotABareHostname(host):
            "\"\(host)\" is not a bare hostname, so it can never match a connection."
        case let .backupRepeatsPrimary(host):
            "\(host) has no backup pin — its backup repeats its primary, so it cannot rotate."
        case let .expiryHasPassed(host, expiry):
            "\(host)'s pins expired at \(expiry); nothing is being pinned."
        case let .expiryIsTooDistant(host, expiry):
            "\(host)'s pins run to \(expiry), longer than the one-year ceiling."
        case let .placeholderPinsAreEnforced(host):
            "\(host) enforces the template's placeholder pins, which match no real key."
        }
    }
}

extension CertificatePinningPolicy {

    /// Everything wrong with this policy as of `date`.
    ///
    /// Empty is the only acceptable answer for a policy an app ships, and the
    /// check belongs to a test rather than to an initialiser: a policy under
    /// construction — a rotation being written, a host being added — is allowed
    /// to be briefly wrong, and the moment that matters is the moment it is
    /// about to be released.
    package func problems(at date: Date) -> [PinningPolicyProblem] {
        var problems: [PinningPolicyProblem] = []
        var seen: Set<String> = []

        for host in hosts {
            let name = host.host.lowercased()
            if !seen.insert(name).inserted {
                problems.append(.duplicateHost(host.host))
            }
            if !Self.isBareHostname(host.host) {
                problems.append(.hostIsNotABareHostname(host.host))
            }
            if !host.pins.canRotate {
                problems.append(.backupRepeatsPrimary(host: host.host))
            }
            if host.hasExpired(at: date) {
                problems.append(.expiryHasPassed(host: host.host, expiry: host.expiry))
            } else if host.expiry.timeIntervalSince(date) > Self.maximumPinLifetime {
                problems.append(.expiryIsTooDistant(host: host.host, expiry: host.expiry))
            }
            if host.enforcement == .enforced, !host.pins.all.isDisjoint(with: PublicKeyPin.placeholders) {
                problems.append(.placeholderPinsAreEnforced(host: host.host))
            }
        }
        return problems
    }

    /// A hostname and nothing else: labels of letters, digits and hyphens,
    /// separated by single dots, with no leading or trailing dot. Deliberately
    /// stricter than DNS allows — an underscore is legal in a DNS label and
    /// illegal in a hostname — because the only thing this string is ever
    /// compared against is a `URLProtectionSpace.host`.
    private static func isBareHostname(_ host: String) -> Bool {
        guard !host.isEmpty, host.count <= 253 else { return false }
        let labels = host.split(separator: ".", omittingEmptySubsequences: false)
        guard labels.count >= 2 else { return false }
        return labels.allSatisfy { label in
            guard !label.isEmpty, label.count <= 63 else { return false }
            guard label.first != "-", label.last != "-" else { return false }
            return label.allSatisfy { $0.isASCII && ($0.isLetter || $0.isNumber || $0 == "-") }
        }
    }
}
